<template>
    <div class="bh-p-10">
        <div class="bh-mb-2">
            <input
                type="text"
                v-model="params.search"
                placeholder="Search..."
                class="bh-border bh-border-solid bh-bg-white bh-p-2 bh-outline-0 bh-border-gray-200 focus:bh-border-gray-200 bh-rounded"
            />
            <button type="button" class="btn mb-4 bh-p-2" @click="datatable.reset()">Reset</button> <br />
        </div>
        <TableCustomized
            ref="datatable"
            :loading="loading"
            :rows="rows"
            :columns="cols"
            :sortable="true"
            :sortColumn="params.sort_column"
            :sortDirection="params.sort_direction"
            :search="params.search"
            :hasCheckbox="true"
            :columnFilter="true"
            fieldVerify="deleted_at"
        >
        <template #travel_dates="data">
            {{ data.value.date_start }} <br> {{ data.value.date_end }}
        </template>
        <template #actions="data">
            <!-- Lista de acciones dropdown tailwind css -->
             
        </template>
        </TableCustomized>
    </div>
</template>
<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue';
import TableCustomized from './components/custom-table.vue';
import '../dist/style.css';

onMounted(() => {
    getUsers();
});

const datatable: any = ref(null);
const loading: any = ref(true);
const total_rows = ref(0);
const rows: any = ref(null);
const cols =
    ref([
        { field: "status", title: "Estatus", filter: true },
        { field: "code", title: "Código", filter: true },
        { field: "created_at", title: "Creado", filter: true, type: "date", width: "8%", formatDate: "D MMM, YYYY" },
        { field: "service_name", title: "Servicio", filter: true, width: "20%", filterColumns: ['customer_name'] },
        { field: "travel_dates", title: "Fechas", filter: true, type: "date", range: true, formatDate: "YYYY-MM-DD" },
        { field: "amount", title: "Tarifas", filter: false, type: "number" },
        { field: "operators", title: "Operadoras", filter: true },
        { field: "date_limit_pay", title: "Límite de pago", filter: true, type: "date", formatDate: "D MMM, YYYY" },
        { field: "agent_name", title: "Agente", filter: true },
        { field: "actions", title: "Acciones", filter: false, sort: false },
    ]) || [];

const changeServer = (data: any) => {
    params.current_page = data.current_page;
    params.pagesize = data.pagesize;
    params.sort_column = data.sort_column;
    params.sort_direction = data.sort_direction;
    params.column_filters = data.column_filters;
    params.search = data.search;

    filterUsers();
};

const params = reactive({
    current_page: 1,
    pagesize: 5,
    sort_column: 'id',
    sort_direction: 'desc',
    column_filters: [],
    search: '',
});

let controller: any;
let timer: any;
const filterUsers = () => {
    clearTimeout(timer);
    timer = setTimeout(() => {
        getUsers();
    }, 300);
};
const getUsers = async () => {
    // cancel request if previous request still pending before next request fire
    // if (controller) {
    //     controller.abort();
    // }
    // controller = new AbortController();
    // const signal = controller.signal;

    // try {
    //     loading.value = true;

    //     const response = await fetch('https://vue3-datatable-document.vercel.app/api/user', {
    //         method: 'POST',
    //         body: JSON.stringify(params),
    //         signal: signal, // Assign the signal to the fetch request
    //     });

    //     const data = await response.json();

    //     rows.value = data?.data;
    //     total_rows.value = data?.meta?.total;
    // } catch {}

    rows.value = [
        {
            "id": 169,
            "code": "S1-3579",
            "reservation_status": {
                "id": 6,
                "title": "CA",
                "name": "Reservación cancelada",
                "color": "#ed1b24"
            },
            "amount": 32499,
            "amount_paid": 4000,
            "divisa": "mxn",
            "date_start": "2023-09-15",
            "date_end": "2023-09-17",
            "date_limit_pay": "2022-08-01",
            "operators": null,
            "customer_id": 155,
            "customer_name": "Jennifer Paola Arce Nuñez",
            "customer_phone": "9871124904",
            "service_id": 18,
            "is_blocked": 0,
            "service_name": "GRAND OASIS CANCUN",
            "service_type_id": 1,
            "service_type_name": "Hoteles",
            "service_exit_place_id": null,
            "service_exit_place_name": null,
            "service_travel_date_id": null,
            "service_travel_date_name": null,
            "service_exit_place_price_id": null,
            "agent_id": 290,
            "agent_name": "GERENCIA",
            "agency_id": 7,
            "agency_name": "NEXTRAVEL",
            "branch_office_id": 8,
            "branch_office_name": "NEXTRAVEL VALLADOLID",
            "registered_id": 290,
            "registered_name": "GERENCIA",
            "agency_metadata": null,
            "aliht_metadata": null,
            "deleted_at": "2023-02-10 19:36:15",
            "created_at": "2022-11-11 18:53:22",
            "updated_at": "2025-04-12 19:46:43",
            "is_passport": false
        },
        {
            "id": 170,
            "code": "S1-3580",
            "reservation_status": {
                "id": 6,
                "title": "CA",
                "name": "Reservación cancelada",
                "color": "#ed1b24"
            },
            "amount": 96251,
            "amount_paid": 45646.8,
            "divisa": "mxn",
            "date_start": "2023-05-19",
            "date_end": "2023-05-21",
            "date_limit_pay": "2023-04-19",
            "operators": null,
            "customer_id": 155,
            "customer_name": "Jennifer Paola Arce Nuñez",
            "customer_phone": "9871124904",
            "service_id": 5,
            "is_blocked": 0,
            "service_name": "ALLEGRO COZUMEL",
            "service_type_id": 1,
            "service_type_name": "Hoteles",
            "service_exit_place_id": null,
            "service_exit_place_name": null,
            "service_travel_date_id": null,
            "service_travel_date_name": null,
            "service_exit_place_price_id": null,
            "agent_id": 290,
            "agent_name": "GERENCIA",
            "agency_id": 7,
            "agency_name": "NEXTRAVEL",
            "branch_office_id": 8,
            "branch_office_name": "NEXTRAVEL VALLADOLID",
            "registered_id": 290,
            "registered_name": "GERENCIA",
            "agency_metadata": null,
            "aliht_metadata": null,
            "deleted_at": "2023-05-12 19:12:27",
            "created_at": "2022-11-11 18:59:38",
            "updated_at": "2025-04-12 19:46:43",
            "is_passport": false
        },
        {
            "id": 228,
            "code": "S1-3668",
            "reservation_status": {
                "id": 6,
                "title": "CA",
                "name": "Reservación cancelada",
                "color": "#ed1b24"
            },
            "amount": 32932,
            "amount_paid": 2000,
            "divisa": "mxn",
            "date_start": "2023-05-18",
            "date_end": "2023-05-21",
            "date_limit_pay": "2022-04-01",
            "operators": null,
            "customer_id": 155,
            "customer_name": "Jennifer Paola Arce Nuñez",
            "customer_phone": "9871124904",
            "service_id": 12,
            "is_blocked": 0,
            "service_name": "GRAND BAHIA PRINCIPE COBA",
            "service_type_id": 1,
            "service_type_name": "Hoteles",
            "service_exit_place_id": null,
            "service_exit_place_name": null,
            "service_travel_date_id": null,
            "service_travel_date_name": null,
            "service_exit_place_price_id": null,
            "agent_id": 290,
            "agent_name": "GERENCIA",
            "agency_id": 7,
            "agency_name": "NEXTRAVEL",
            "branch_office_id": 8,
            "branch_office_name": "NEXTRAVEL VALLADOLID",
            "registered_id": 290,
            "registered_name": "GERENCIA",
            "agency_metadata": null,
            "aliht_metadata": null,
            "deleted_at": "2023-05-10 22:20:16",
            "created_at": "2022-11-26 00:22:46",
            "updated_at": "2025-04-12 19:46:43",
            "is_passport": false
        },
        {
            "id": 250,
            "code": "S1-3699",
            "reservation_status": {
                "id": 3,
                "title": "PA",
                "name": "Liquidado por cliente",
                "color": "#006fc8"
            },
            "amount": 12609,
            "amount_paid": 12609,
            "divisa": "mxn",
            "date_start": "2023-04-27",
            "date_end": "2023-04-30",
            "date_limit_pay": "2022-03-22",
            "operators": "ALIHT",
            "customer_id": 220,
            "customer_name": "XOCHITL CABRERA TOLEDO",
            "customer_phone": "9858085139",
            "service_id": 42,
            "is_blocked": 0,
            "service_name": "OCEAN RIVIERA PARADISE",
            "service_type_id": 1,
            "service_type_name": "Hoteles",
            "service_exit_place_id": null,
            "service_exit_place_name": null,
            "service_travel_date_id": null,
            "service_travel_date_name": null,
            "service_exit_place_price_id": null,
            "agent_id": 290,
            "agent_name": "GERENCIA",
            "agency_id": 7,
            "agency_name": "NEXTRAVEL",
            "branch_office_id": 8,
            "branch_office_name": "NEXTRAVEL VALLADOLID",
            "registered_id": 290,
            "registered_name": "GERENCIA",
            "agency_metadata": "[{\"total\":\"12609.00\",\"total_net\":\"10717.65\",\"pass_id\":397,\"total_commission\":\"1891.35\"}]",
            "aliht_metadata": "[{\"total\":\"10717.65\",\"pass_id\":397,\"total_commission\":\"1891.35\",\"total_commission_gain\":\"0.00\"}]",
            "deleted_at": null,
            "created_at": "2022-12-01 16:09:04",
            "updated_at": "2025-04-12 19:41:03",
            "is_passport": false
        },
        {
            "id": 295,
            "code": "S1-3774",
            "reservation_status": {
                "id": 1,
                "title": "OR",
                "name": "On Request",
                "color": "#fb3"
            },
            "amount": 172140,
            "amount_paid": 18000,
            "divisa": "mxn",
            "date_start": "2023-07-28",
            "date_end": "2023-07-30",
            "date_limit_pay": "2023-06-28",
            "operators": null,
            "customer_id": 219,
            "customer_name": "DAVID ALONSO VILLAGÓMEZ RODRÍGUEZ",
            "customer_phone": "9831396133",
            "service_id": 36,
            "is_blocked": 0,
            "service_name": "BARCELO GRAND RESORT",
            "service_type_id": 1,
            "service_type_name": "Hoteles",
            "service_exit_place_id": null,
            "service_exit_place_name": null,
            "service_travel_date_id": null,
            "service_travel_date_name": null,
            "service_exit_place_price_id": null,
            "agent_id": 290,
            "agent_name": "GERENCIA",
            "agency_id": 7,
            "agency_name": "NEXTRAVEL",
            "branch_office_id": 8,
            "branch_office_name": "NEXTRAVEL VALLADOLID",
            "registered_id": 290,
            "registered_name": "GERENCIA",
            "agency_metadata": null,
            "aliht_metadata": null,
            "deleted_at": null,
            "created_at": "2022-12-17 16:46:14",
            "updated_at": "2025-04-12 19:41:03",
            "is_passport": false
        },
        {
            "id": 313,
            "code": "S1-3805",
            "reservation_status": {
                "id": 6,
                "title": "CA",
                "name": "Reservación cancelada",
                "color": "#ed1b24"
            },
            "amount": 100000,
            "amount_paid": 12765,
            "divisa": "mxn",
            "date_start": "2023-07-01",
            "date_end": "2023-07-04",
            "date_limit_pay": "2023-03-20",
            "operators": null,
            "customer_id": 258,
            "customer_name": "Francisco Fabián Luevano Macias",
            "customer_phone": "4921747269",
            "service_id": 223,
            "is_blocked": 0,
            "service_name": "SIN HOTEL XXXX",
            "service_type_id": 1,
            "service_type_name": "Hoteles",
            "service_exit_place_id": null,
            "service_exit_place_name": null,
            "service_travel_date_id": null,
            "service_travel_date_name": null,
            "service_exit_place_price_id": null,
            "agent_id": 290,
            "agent_name": "GERENCIA",
            "agency_id": 7,
            "agency_name": "NEXTRAVEL",
            "branch_office_id": 8,
            "branch_office_name": "NEXTRAVEL VALLADOLID",
            "registered_id": 290,
            "registered_name": "GERENCIA",
            "agency_metadata": null,
            "aliht_metadata": null,
            "deleted_at": "2023-04-17 17:51:35",
            "created_at": "2022-12-20 17:52:52",
            "updated_at": "2025-04-12 19:46:43",
            "is_passport": false
        },
        {
            "id": 320,
            "code": "S1-3817",
            "reservation_status": {
                "id": 6,
                "title": "CA",
                "name": "Reservación cancelada",
                "color": "#ed1b24"
            },
            "amount": 20635,
            "amount_paid": 2000,
            "divisa": "mxn",
            "date_start": "2023-09-15",
            "date_end": "2023-09-17",
            "date_limit_pay": "2023-08-01",
            "operators": null,
            "customer_id": 155,
            "customer_name": "Jennifer Paola Arce Nuñez",
            "customer_phone": "9871124904",
            "service_id": 18,
            "is_blocked": 0,
            "service_name": "GRAND OASIS CANCUN",
            "service_type_id": 1,
            "service_type_name": "Hoteles",
            "service_exit_place_id": null,
            "service_exit_place_name": null,
            "service_travel_date_id": null,
            "service_travel_date_name": null,
            "service_exit_place_price_id": null,
            "agent_id": 290,
            "agent_name": "GERENCIA",
            "agency_id": 7,
            "agency_name": "NEXTRAVEL",
            "branch_office_id": 8,
            "branch_office_name": "NEXTRAVEL VALLADOLID",
            "registered_id": 290,
            "registered_name": "GERENCIA",
            "agency_metadata": null,
            "aliht_metadata": null,
            "deleted_at": "2023-02-10 19:35:35",
            "created_at": "2022-12-22 19:19:38",
            "updated_at": "2025-04-12 19:46:43",
            "is_passport": false
        },
        {
            "id": 746,
            "code": "S12023-746",
            "reservation_status": {
                "id": 3,
                "title": "PA",
                "name": "Liquidado por cliente",
                "color": "#006fc8"
            },
            "amount": 9310,
            "amount_paid": 9310,
            "divisa": "mxn",
            "date_start": "2023-04-07",
            "date_end": "2023-04-09",
            "date_limit_pay": "2023-03-01",
            "operators": "ALIHT",
            "customer_id": 2710,
            "customer_name": "Georgina Gamboa",
            "customer_phone": "9993648168",
            "service_id": 42,
            "is_blocked": 0,
            "service_name": "OCEAN RIVIERA PARADISE",
            "service_type_id": 1,
            "service_type_name": "Hoteles",
            "service_exit_place_id": null,
            "service_exit_place_name": null,
            "service_travel_date_id": null,
            "service_travel_date_name": null,
            "service_exit_place_price_id": null,
            "agent_id": 290,
            "agent_name": "GERENCIA",
            "agency_id": 7,
            "agency_name": "NEXTRAVEL",
            "branch_office_id": 8,
            "branch_office_name": "NEXTRAVEL VALLADOLID",
            "registered_id": 290,
            "registered_name": "GERENCIA",
            "agency_metadata": "[{\"total\":\"9310.00\",\"total_net\":\"7913.50\",\"pass_id\":295,\"total_commission\":\"1396.50\"}]",
            "aliht_metadata": "[{\"total\":\"7913.50\",\"pass_id\":295,\"total_commission\":\"1396.50\",\"total_commission_gain\":\"0.00\"}]",
            "deleted_at": null,
            "created_at": "2023-01-30 23:50:18",
            "updated_at": "2025-04-12 19:41:05",
            "is_passport": false
        },
        {
            "id": 757,
            "code": "S12023-757",
            "reservation_status": {
                "id": 2,
                "title": "CO",
                "name": "Reservación Confirmada",
                "color": "#00c851"
            },
            "amount": 116794,
            "amount_paid": 116794,
            "divisa": "mxn",
            "date_start": "2023-11-16",
            "date_end": "2023-11-19",
            "date_limit_pay": "2023-10-16",
            "operators": "RECORD",
            "customer_id": 488,
            "customer_name": "Ariadna Yunuen Parangueo García",
            "customer_phone": "5511556931",
            "service_id": 29,
            "is_blocked": 0,
            "service_name": "HOTEL THE PYRAMID AT GRAND OASIS",
            "service_type_id": 1,
            "service_type_name": "Hoteles",
            "service_exit_place_id": null,
            "service_exit_place_name": null,
            "service_travel_date_id": null,
            "service_travel_date_name": null,
            "service_exit_place_price_id": null,
            "agent_id": 290,
            "agent_name": "GERENCIA",
            "agency_id": 7,
            "agency_name": "NEXTRAVEL",
            "branch_office_id": 8,
            "branch_office_name": "NEXTRAVEL VALLADOLID",
            "registered_id": 290,
            "registered_name": "GERENCIA",
            "agency_metadata": "[{\"total\":\"33600.00\",\"total_net\":\"28224.00\",\"pass_id\":3323,\"total_commission\":\"5376.00\"},{\"total\":\"32700.00\",\"total_net\":\"27468.00\",\"pass_id\":3324,\"total_commission\":\"5232.00\"},{\"total\":\"33600.00\",\"total_net\":\"28224.00\",\"pass_id\":3325,\"total_commission\":\"5376.00\"},{\"total\":\"11793.50\",\"total_net\":\"9906.54\",\"pass_id\":3326,\"total_commission\":\"1886.96\"}]",
            "aliht_metadata": "[{\"total\":\"28224.00\",\"pass_id\":3323,\"total_commission\":\"5376.00\",\"total_commission_gain\":\"0.00\"},{\"total\":\"27468.00\",\"pass_id\":3324,\"total_commission\":\"5232.00\",\"total_commission_gain\":\"0.00\"},{\"total\":\"28224.00\",\"pass_id\":3325,\"total_commission\":\"5376.00\",\"total_commission_gain\":\"0.00\"},{\"total\":\"9906.54\",\"pass_id\":3326,\"total_commission\":\"1886.96\",\"total_commission_gain\":\"0.00\"}]",
            "deleted_at": null,
            "created_at": "2023-02-01 00:17:10",
            "updated_at": "2025-04-12 19:41:06",
            "is_passport": false
        },
        {
            "id": 780,
            "code": "S12023-780",
            "reservation_status": {
                "id": 3,
                "title": "PA",
                "name": "Liquidado por cliente",
                "color": "#006fc8"
            },
            "amount": 7831,
            "amount_paid": 7831,
            "divisa": "mxn",
            "date_start": "2023-04-07",
            "date_end": "2023-04-09",
            "date_limit_pay": "2023-03-01",
            "operators": "ALIHT",
            "customer_id": 2710,
            "customer_name": "Georgina Gamboa",
            "customer_phone": "9993648168",
            "service_id": 42,
            "is_blocked": 0,
            "service_name": "OCEAN RIVIERA PARADISE",
            "service_type_id": 1,
            "service_type_name": "Hoteles",
            "service_exit_place_id": null,
            "service_exit_place_name": null,
            "service_travel_date_id": null,
            "service_travel_date_name": null,
            "service_exit_place_price_id": null,
            "agent_id": 290,
            "agent_name": "GERENCIA",
            "agency_id": 7,
            "agency_name": "NEXTRAVEL",
            "branch_office_id": 8,
            "branch_office_name": "NEXTRAVEL VALLADOLID",
            "registered_id": 290,
            "registered_name": "GERENCIA",
            "agency_metadata": "[{\"total\":\"7832.00\",\"total_net\":\"6657.20\",\"pass_id\":885,\"total_commission\":\"1174.80\"}]",
            "aliht_metadata": "[{\"total\":\"6657.20\",\"pass_id\":885,\"total_commission\":\"1174.80\",\"total_commission_gain\":\"0.00\"}]",
            "deleted_at": null,
            "created_at": "2023-02-03 00:30:36",
            "updated_at": "2025-04-12 19:41:06",
            "is_passport": false
        },
        {
            "id": 910,
            "code": "S12023-910",
            "reservation_status": {
                "id": 3,
                "title": "PA",
                "name": "Liquidado por cliente",
                "color": "#006fc8"
            },
            "amount": 10785,
            "amount_paid": 10785,
            "divisa": "mxn",
            "date_start": "2023-04-07",
            "date_end": "2023-04-09",
            "date_limit_pay": "2023-02-28",
            "operators": "ALIHT",
            "customer_id": 2710,
            "customer_name": "Georgina Gamboa",
            "customer_phone": "9993648168",
            "service_id": 42,
            "is_blocked": 0,
            "service_name": "OCEAN RIVIERA PARADISE",
            "service_type_id": 1,
            "service_type_name": "Hoteles",
            "service_exit_place_id": null,
            "service_exit_place_name": null,
            "service_travel_date_id": null,
            "service_travel_date_name": null,
            "service_exit_place_price_id": null,
            "agent_id": 290,
            "agent_name": "GERENCIA",
            "agency_id": 7,
            "agency_name": "NEXTRAVEL",
            "branch_office_id": 8,
            "branch_office_name": "NEXTRAVEL VALLADOLID",
            "registered_id": 290,
            "registered_name": "GERENCIA",
            "agency_metadata": "[{\"total\":\"10785.00\",\"total_net\":\"9167.25\",\"pass_id\":622,\"total_commission\":\"1617.75\"}]",
            "aliht_metadata": "[{\"total\":\"9167.25\",\"pass_id\":622,\"total_commission\":\"1617.75\",\"total_commission_gain\":\"0.00\"}]",
            "deleted_at": null,
            "created_at": "2023-02-14 16:48:52",
            "updated_at": "2025-04-12 19:41:06",
            "is_passport": false
        },
        {
            "id": 6509,
            "code": "S12024-6509",
            "reservation_status": {
                "id": 2,
                "title": "CO",
                "name": "Reservación Confirmada",
                "color": "#00c851"
            },
            "amount": 11753.12,
            "amount_paid": 11753.12,
            "divisa": "mxn",
            "date_start": "2024-06-03",
            "date_end": "2024-06-06",
            "date_limit_pay": "2024-05-07",
            "operators": "OUTLET DE VERANO",
            "customer_id": 5720,
            "customer_name": "GIOVANNA SOSA BELTRAN",
            "customer_phone": "9993613651",
            "service_id": 392,
            "is_blocked": 0,
            "service_name": "Hotel Catalonia Yucatán Beach",
            "service_type_id": 1,
            "service_type_name": "Hoteles",
            "service_exit_place_id": null,
            "service_exit_place_name": null,
            "service_travel_date_id": null,
            "service_travel_date_name": null,
            "service_exit_place_price_id": null,
            "agent_id": 290,
            "agent_name": "GERENCIA",
            "agency_id": 7,
            "agency_name": "NEXTRAVEL",
            "branch_office_id": 8,
            "branch_office_name": "NEXTRAVEL VALLADOLID",
            "registered_id": 290,
            "registered_name": "GERENCIA",
            "agency_metadata": "[{\"total\":\"11753.12\",\"total_net\":\"10342.75\",\"pass_id\":8215,\"total_commission\":\"1410.37\"}]",
            "aliht_metadata": "[{\"total\":\"10107.68\",\"pass_id\":8215,\"total_commission\":\"1645.44\",\"total_commission_gain\":\"235.06\"}]",
            "deleted_at": null,
            "created_at": "2024-05-06 18:53:01",
            "updated_at": "2025-04-12 19:41:28",
            "is_passport": false
        },
        {
            "id": 6564,
            "code": "S12024-6564",
            "reservation_status": {
                "id": 2,
                "title": "CO",
                "name": "Reservación Confirmada",
                "color": "#00c851"
            },
            "amount": 6221,
            "amount_paid": 6221,
            "divisa": "mxn",
            "date_start": "2024-06-07",
            "date_end": "2024-06-09",
            "date_limit_pay": "2024-05-09",
            "operators": "AZABACHE",
            "customer_id": 663,
            "customer_name": "MAYRA PATRICIA BURGOS CAAMAL",
            "customer_phone": "9861031284",
            "service_id": 8,
            "is_blocked": 0,
            "service_name": "GRAND PARK ROYAL COZUMEL",
            "service_type_id": 1,
            "service_type_name": "Hoteles",
            "service_exit_place_id": null,
            "service_exit_place_name": null,
            "service_travel_date_id": null,
            "service_travel_date_name": null,
            "service_exit_place_price_id": null,
            "agent_id": 290,
            "agent_name": "GERENCIA",
            "agency_id": 7,
            "agency_name": "NEXTRAVEL",
            "branch_office_id": 8,
            "branch_office_name": "NEXTRAVEL VALLADOLID",
            "registered_id": 290,
            "registered_name": "GERENCIA",
            "agency_metadata": "[{\"total\":\"5919.00\",\"total_net\":\"4971.96\",\"pass_id\":8340,\"total_commission\":\"947.04\"}]",
            "aliht_metadata": "[{\"total\":\"4971.96\",\"pass_id\":8340,\"total_commission\":\"947.04\",\"total_commission_gain\":\"0.00\"}]",
            "deleted_at": null,
            "created_at": "2024-05-08 22:30:29",
            "updated_at": "2025-04-12 19:41:28",
            "is_passport": false
        },
        {
            "id": 6625,
            "code": "S12024-6625",
            "reservation_status": {
                "id": 6,
                "title": "CA",
                "name": "Reservación cancelada",
                "color": "#ed1b24"
            },
            "amount": 8400,
            "amount_paid": 0,
            "divisa": "mxn",
            "date_start": "2024-05-03",
            "date_end": "2024-05-05",
            "date_limit_pay": "2024-05-15",
            "operators": "HOSTECH",
            "customer_id": 133,
            "customer_name": "Jafet Abimael Tun Uc",
            "customer_phone": "9851223898",
            "service_id": 175,
            "is_blocked": 0,
            "service_name": "ALLEGRO PLAYACAR",
            "service_type_id": 1,
            "service_type_name": "Hoteles",
            "service_exit_place_id": null,
            "service_exit_place_name": null,
            "service_travel_date_id": null,
            "service_travel_date_name": null,
            "service_exit_place_price_id": null,
            "agent_id": 290,
            "agent_name": "GERENCIA",
            "agency_id": 7,
            "agency_name": "NEXTRAVEL",
            "branch_office_id": 8,
            "branch_office_name": "NEXTRAVEL VALLADOLID",
            "registered_id": 290,
            "registered_name": "GERENCIA",
            "agency_metadata": "[{\"total\":\"10500.00\",\"total_net\":\"8820.00\",\"pass_id\":8412,\"total_commission\":\"1680.00\"}]",
            "aliht_metadata": "[{\"total\":\"8820.00\",\"pass_id\":8412,\"total_commission\":\"1680.00\",\"total_commission_gain\":\"0.00\"}]",
            "deleted_at": "2024-05-14 18:58:42",
            "created_at": "2024-05-14 18:54:37",
            "updated_at": "2025-04-12 19:47:40",
            "is_passport": false
        },
        {
            "id": 6729,
            "code": "S12024-6729",
            "reservation_status": {
                "id": 2,
                "title": "CO",
                "name": "Reservación Confirmada",
                "color": "#00c851"
            },
            "amount": 5170,
            "amount_paid": 5170,
            "divisa": "mxn",
            "date_start": "2024-06-28",
            "date_end": "2024-06-29",
            "date_limit_pay": "2024-06-10",
            "operators": "HOSTECH",
            "customer_id": 1516,
            "customer_name": "Gener Alejandro Ramírez Santana",
            "customer_phone": "9981520671",
            "service_id": 36,
            "is_blocked": 0,
            "service_name": "BARCELO GRAND RESORT",
            "service_type_id": 1,
            "service_type_name": "Hoteles",
            "service_exit_place_id": null,
            "service_exit_place_name": null,
            "service_travel_date_id": null,
            "service_travel_date_name": null,
            "service_exit_place_price_id": null,
            "agent_id": 290,
            "agent_name": "GERENCIA",
            "agency_id": 7,
            "agency_name": "NEXTRAVEL",
            "branch_office_id": 8,
            "branch_office_name": "NEXTRAVEL VALLADOLID",
            "registered_id": 290,
            "registered_name": "GERENCIA",
            "agency_metadata": "[{\"total\":\"5336.00\",\"total_net\":\"4482.24\",\"pass_id\":8554,\"total_commission\":\"853.76\"}]",
            "aliht_metadata": "[{\"total\":\"4482.24\",\"pass_id\":8554,\"total_commission\":\"853.76\",\"total_commission_gain\":\"0.00\"}]",
            "deleted_at": null,
            "created_at": "2024-05-20 18:29:38",
            "updated_at": "2025-04-12 19:41:28",
            "is_passport": false
        },
        {
            "id": 13502,
            "code": "S12025-13502",
            "reservation_status": {
                "id": 2,
                "title": "CO",
                "name": "Reservación Confirmada",
                "color": "#00c851"
            },
            "amount": 37210,
            "amount_paid": 5000,
            "divisa": "mxn",
            "date_start": "2025-11-28",
            "date_end": "2025-12-02",
            "date_limit_pay": "2025-11-01",
            "operators": "HOSTECH",
            "customer_id": 8654,
            "customer_name": "Cristopher German Arroyo",
            "customer_phone": "9881092602",
            "service_id": 88,
            "is_blocked": 0,
            "service_name": "Generations Riviera Maya",
            "service_type_id": 1,
            "service_type_name": "Hoteles",
            "service_exit_place_id": null,
            "service_exit_place_name": null,
            "service_travel_date_id": null,
            "service_travel_date_name": null,
            "service_exit_place_price_id": null,
            "agent_id": 290,
            "agent_name": "GERENCIA",
            "agency_id": 7,
            "agency_name": "NEXTRAVEL",
            "branch_office_id": 8,
            "branch_office_name": "NEXTRAVEL VALLADOLID",
            "registered_id": 290,
            "registered_name": "GERENCIA",
            "agency_metadata": "[{\"total\":\"36073.00\",\"total_net\":\"30301.32\",\"pass_id\":17113,\"total_commission\":\"5771.68\"}]",
            "aliht_metadata": "[{\"total\":\"29940.59\",\"pass_id\":17113,\"total_commission\":\"6132.41\",\"total_commission_gain\":\"360.73\"}]",
            "deleted_at": null,
            "created_at": "2025-09-30 20:25:50",
            "updated_at": "2025-09-30 20:27:10",
            "is_passport": false
        },
        {
            "id": 13816,
            "code": "S1-13816",
            "reservation_status": {
                "id": 1,
                "title": "OR",
                "name": "On Request",
                "color": "#fb3"
            },
            "amount": 7500,
            "amount_paid": 0,
            "divisa": "mxn",
            "date_start": "2025-12-24",
            "date_end": "2025-12-31",
            "date_limit_pay": "2025-11-30",
            "operators": null,
            "customer_id": 8797,
            "customer_name": "Mayra Alejandra López Barrientos",
            "customer_phone": "9851405050",
            "service_id": 4,
            "is_blocked": 0,
            "service_name": "HOTEL SAN FRANCISCO CENTRO HISTORICO",
            "service_type_id": 1,
            "service_type_name": "Hoteles",
            "service_exit_place_id": null,
            "service_exit_place_name": null,
            "service_travel_date_id": null,
            "service_travel_date_name": null,
            "service_exit_place_price_id": null,
            "agent_id": 290,
            "agent_name": "GERENCIA",
            "agency_id": 7,
            "agency_name": "NEXTRAVEL",
            "branch_office_id": 8,
            "branch_office_name": "NEXTRAVEL VALLADOLID",
            "registered_id": 290,
            "registered_name": "GERENCIA",
            "agency_metadata": null,
            "aliht_metadata": null,
            "deleted_at": null,
            "created_at": "2025-11-06 12:00:48",
            "updated_at": "2025-11-06 12:00:49",
            "is_passport": false
        },
        {
            "id": 13818,
            "code": "S1-13818",
            "reservation_status": {
                "id": 1,
                "title": "OR",
                "name": "On Request",
                "color": "#fb3"
            },
            "amount": 0,
            "amount_paid": 0,
            "divisa": "mxn",
            "date_start": "2025-12-23",
            "date_end": "2025-12-30",
            "date_limit_pay": "2025-11-21",
            "operators": null,
            "customer_id": 8797,
            "customer_name": "Mayra Alejandra López Barrientos",
            "customer_phone": "9851405050",
            "service_id": 4,
            "is_blocked": 0,
            "service_name": "HOTEL SAN FRANCISCO CENTRO HISTORICO",
            "service_type_id": 1,
            "service_type_name": "Hoteles",
            "service_exit_place_id": null,
            "service_exit_place_name": null,
            "service_travel_date_id": null,
            "service_travel_date_name": null,
            "service_exit_place_price_id": null,
            "agent_id": 290,
            "agent_name": "GERENCIA",
            "agency_id": 7,
            "agency_name": "NEXTRAVEL",
            "branch_office_id": 8,
            "branch_office_name": "NEXTRAVEL VALLADOLID",
            "registered_id": 290,
            "registered_name": "GERENCIA",
            "agency_metadata": null,
            "aliht_metadata": null,
            "deleted_at": null,
            "created_at": "2025-11-06 12:05:57",
            "updated_at": "2025-11-06 12:05:58",
            "is_passport": false
        }
    ];

    loading.value = false;
};
</script>
